### ISSUE TITLE
`ACME  "directory"` not working when in `RootJail`

### ISSUE THREAD

**Issue by nagyrobi** [graygnuorg/pound#6] opened 2023-03-28 07:55 UTC
@graygnuorg thank you for keeping this project alive.

I've recently migrated under FreeBSD the from the old aspis version to your new 4.6 release (downloaded and compiled myself).

Wile trying out the ACME functionality, I found that I always get 404 error for the challenge. Doing manual steps to investigate, and found that pound always returns 404 despite a file being placed in the correct directory. Config is like:

```
User		"nobody"
Group		"nobody"
RootJail	"/var/jail/pound/"
PIDFile		"/var/run/pound.pid"

ListenHTTP
	Address 127.0.0.1
	Port    9080  #access is done through port forwards from WAN to here
	LogLevel 5
	xHTTP 3
	Err404 "/var/jail/pound/err404.txt"
	Err413 "/var/jail/pound/err413.txt"
	Err414 "/var/jail/pound/err414.txt"
	Err500 "/var/jail/pound/err500.txt"
	Err501 "/var/jail/pound/err501.txt"
	Err503 "/var/jail/pound/err503.txt"

	Service
		HeadRequire "Host: someotherhost.example.com"
		Backend
			Address 192.168.1.22
			Port    80
			TimeOut 900
		End
	End

	ACME "/var/jail/pound/acme"

	...
```
Placed a file under `/var/jail/pound/acme` (with `echo test > /var/jail/pound/acme/aaa.txt`) and trying to access through a browser via `http://example.com/.well-known/acme-challenge/aaa.txt` results in Error404. Also tried to place the file at `/var/jail/pound/acme/.well-known/acme-challenge/aaa.txt` but still 404.

In the log only:
```
Mar 28 10:15:34 | pound | 68281 | example.com 192.168.0.1 - - [28/Mar/2023:10:15:34 +0200]  "GET /.well-known/acme-challenge/aaa.txt HTTP/1.1" 404 - "" "Mozilla/5.0  (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0"  ((acme) -> acme:/var/jail/pound/acme/$1) 0.000 sec

```

Of course if I omit or modify `.well-known/acme-challenge` from the URL I get Error503 so it looks like the ACME listener properly detects it, but doesn't serve the file.

Commenting out the `RootJail` configuration seems to fix it. But I don't see why, as the ACME directory is within the jail, and Err files are served well from there.

**Comment by graygnuorg** [comment] 2023-03-28 16:06
Thanks for reporting that.  The problem is that pound tries to open the acme directory too late (after chrooting), and then it is already not visible. I fixed this in commit c2fb6aeb02571b53f6ad39d6467b558abc5394f2. Please pull and give it a try.

**Comment by nagyrobi** [comment] 2023-03-28 16:26
Downloaded the repo, unzipped, followed the steps from the readme but getting an error with `make`:

```
root@bsd123:~/pound-4.6-dev # make
make  all-recursive
Making all in src
make  all-am
cc -DHAVE_CONFIG_H -I. -I..  -DSYSCONFDIR=\"/usr/local/etc\" -DLOCALSTATEDIR=\"/usr/local/var\" -DPKGDATADIR=\"/usr/local/share/pound\"  -g -O2 -pthread -g -O2 -MT poundctl.o -MD -MP -MF .deps/poundctl.Tpo -c -o poundctl.o poundctl.c
mv -f .deps/poundctl.Tpo .deps/poundctl.Po
make[3]: don't know how to make ./libpound.a. Stop

make[3]: stopped in /root/pound-4.6-dev/src
*** Error code 2
*** Error code 1
*** Error code 1
```

**Comment by graygnuorg** [comment] 2023-03-28 17:30
Please apply this patch as well: 62f59fe386b05727b6004fd593990e5d7f76b671

**Comment by nagyrobi** [comment] 2023-03-28 18:35
Success!

**Comment by nagyrobi** [comment] 2023-03-28 18:47
A question related to ACME: is the order of the objects defined in the configuration taken into account during operation?
I mean, is the config processed like most firewalls do, like from top to bottom first match applies?

Because, in my case, I have an ACME configuration running on the same machine with `pound`, however, I also have a few machines which are handling their own ACME certificate renewal procedures, their encryption stuff is not handled by `pound` (certs are used for some other kind of communication). These need to be reachable directly by Let's Encrypt on HTTP for the challenge.

So for these, I'd just set up simple `ListenHTTP` service backends without redirect to HTTPS, and pound shouldn't intercept `.well-known/acme-challenge` for them.

If you look at the config above, that was my attempt. `someotherhost.example.com` would be matched by a service before the `ACME` directive, which wouldn't process it.

Do you think that's fine like that?

**Comment by nagyrobi** [comment] 2023-03-28 19:05
Thank you. Meanwhile I've found in the doc: _Services are tried in the same order as they are defined in configuration._ It would be very nice if this feature would remain in the future.

> instead of `HeadRequire` I'd suggest using `Host`

Thanks, I've changed all my services to the new syntax.

**Comment by graygnuorg** [comment] 2023-03-28 19:07
Sure, it will remain so.

**Comment by nagyrobi** [comment] 2023-03-28 19:08
Just a tip: maybe you'd like to enable Discussions function for this repo so we don't spam your issues with Q&A.

**Comment by graygnuorg** [comment] 2023-03-28 19:17
Nice idea. I've enabled it. I'm closing this issue then.

**Closed as completed** 2023-03-28 19:17 UTC
